version: '3.8'

services:
  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - my-network

  nginx:
    image: nginx:latest
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "81:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
